name: Check for burn day

on:
  schedule:
  - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Fetch latest data
      run: npm ci && npm start
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated for diff"
        git config user.email "diff@protonmail.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push